### ISSUE TITLE
BUG : language error 

### ISSUE THREAD

**Issue by RATZogun** [h4h13/paisa-app#23]
Error: Bad state: No element
                          Stack: #0      ListBase.firstWhere (dart:collection/list.dart:132)
#1      AppLanguageChanger.build.<anonymous closure> (package:paisa/features/settings/presentation/widgets/app_language_changer.dart:45)
#2      _ValueListenableBuilderState.build (package:flutter/src/widgets/value_listenable_builder.dart:141)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5743)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5631)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5794)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5785)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
#14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#17     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7049)
#18     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7061)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
#26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
#27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
#37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5794)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
#39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
#40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5785)
#41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
#46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
#47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
#52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
#53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
#54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
#57     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5794)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
#59     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
#60     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5785)
#61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
#62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
#66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
#67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
#68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#70     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:982)
#71     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:967)
#72     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3038)
#73     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:959)
#74     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:367)
#75     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2738)
#76     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1108)
#77     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2738)
#78     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:356)
#79     RenderSliverMultiBoxAdaptor.insertAndLayoutLeadingChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:474)
#80     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:130)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#82     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:124)
#83     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:330)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#85     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:609)
#86     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1877)
#87     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1834)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117)
#92     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117)
#94     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117)
#96     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117)
#98     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117)
#104    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1476)
#105    RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#106    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:178)
#107    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1105)
#108    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242)
#109    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:409)
#110    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2465)
#111    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1062)
#112    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1075)
#113    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:609)
#114    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1178)
#115    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475)
#116    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397)
#117    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318)
#118    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176)
#119    _invoke (dart:ui/hooks.dart:312)
#120    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:427)
#121    _drawFrame (dart:ui/hooks.dart:283)

**Comment by h4h13** [comment]
hey @RATZogun  is this still an issue
